services:
  - type: web
    name: equilibria-labs-api
    env: node
    rootDirectory: apps/api
    buildCommand: pnpm install && pnpm build:types && pnpm build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
    skip: # Skip deployment if changes are only in web directory
      - apps/web/**/* 