services:
  - type: web
    name: equilibria-labs-api
    env: node
    rootDirectory: apps/api
    buildCommand: cd ../.. && pnpm install && pnpm build:types && cd apps/api && pnpm build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production 